/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Market;

/**
 *
 * @author ADMIN
 */
public class CustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InformationBox = new javax.swing.JPanel();
        Search = new javax.swing.JLabel();
        SearchForm = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        TableBox = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        CustomerTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        InformationBox.setBackground(new java.awt.Color(255, 102, 0));

        Search.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Tìm khách hàng");

        SearchForm.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        SearchForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFormActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(255, 132, 51));
        SearchButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setIcon(new javax.swing.ImageIcon("D:\\LongNg(Aptec)\\JAVA_B189_196\\JavaProject1\\src\\main\\java\\Icon\\search.png")); // NOI18N
        SearchButton.setText("Tìm kiếm");
        SearchButton.setMargin(new java.awt.Insets(8, 14, 8, 14));

        AddButton.setBackground(new java.awt.Color(255, 132, 51));
        AddButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setIcon(new javax.swing.ImageIcon("D:\\LongNg(Aptec)\\JAVA_B189_196\\JavaProject1\\src\\main\\java\\Icon\\adduser.png")); // NOI18N
        AddButton.setText("Thêm mới");
        AddButton.setMargin(new java.awt.Insets(8, 14, 8, 14));

        EditButton.setBackground(new java.awt.Color(255, 132, 51));
        EditButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        EditButton.setForeground(new java.awt.Color(255, 255, 255));
        EditButton.setIcon(new javax.swing.ImageIcon("D:\\LongNg(Aptec)\\JAVA_B189_196\\JavaProject1\\src\\main\\java\\Icon\\edit.png")); // NOI18N
        EditButton.setText("Sửa");
        EditButton.setMargin(new java.awt.Insets(8, 14, 8, 14));
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(255, 132, 51));
        DeleteButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setIcon(new javax.swing.ImageIcon("D:\\LongNg(Aptec)\\JAVA_B189_196\\JavaProject1\\src\\main\\java\\Icon\\delete.png")); // NOI18N
        DeleteButton.setText("Xoá");
        DeleteButton.setMargin(new java.awt.Insets(8, 14, 8, 14));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InformationBoxLayout = new javax.swing.GroupLayout(InformationBox);
        InformationBox.setLayout(InformationBoxLayout);
        InformationBoxLayout.setHorizontalGroup(
            InformationBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationBoxLayout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformationBoxLayout.createSequentialGroup()
                .addContainerGap(448, Short.MAX_VALUE)
                .addComponent(Search)
                .addGap(16, 16, 16)
                .addComponent(SearchForm, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(SearchButton)
                .addGap(428, 428, 428))
        );
        InformationBoxLayout.setVerticalGroup(
            InformationBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationBoxLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(InformationBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search)
                    .addComponent(SearchForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addGap(24, 24, 24)
                .addGroup(InformationBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(EditButton)
                    .addComponent(DeleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Title.setText("DANH SÁCH KHÁCH HÀNG");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "SĐT", "Email", "Địa chỉ", "Ngày tạo"
            }
        ));
        CustomerTable.setViewportView(jTable1);

        javax.swing.GroupLayout TableBoxLayout = new javax.swing.GroupLayout(TableBox);
        TableBox.setLayout(TableBoxLayout);
        TableBoxLayout.setHorizontalGroup(
            TableBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TableBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(356, 356, 356))
            .addComponent(CustomerTable, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        TableBoxLayout.setVerticalGroup(
            TableBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableBoxLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Title)
                .addGap(24, 24, 24)
                .addComponent(CustomerTable, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InformationBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TableBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(InformationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TableBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFormActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JScrollPane CustomerTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JPanel InformationBox;
    private javax.swing.JLabel Search;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchForm;
    private javax.swing.JPanel TableBox;
    private javax.swing.JLabel Title;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
