/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Market;

/**
 *
 * @author ADMIN
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boxProducts = new javax.swing.JPanel();
        ManageProducts = new javax.swing.JLabel();
        FormProdID = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Suplier = new javax.swing.JLabel();
        FormCategory = new javax.swing.JComboBox<>();
        SearchButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        TableProducts = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ProductList = new javax.swing.JLabel();
        FormCategory2 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1024, 727));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 800));

        boxProducts.setBackground(new java.awt.Color(204, 204, 204));
        boxProducts.setPreferredSize(new java.awt.Dimension(1200, 775));
        boxProducts.setRequestFocusEnabled(false);

        ManageProducts.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ManageProducts.setText("QUẢN LÝ SẢN PHẨM");

        FormProdID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FormProdID.setToolTipText("");
        FormProdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormProdIDActionPerformed(evt);
            }
        });

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Name.setText("Nhà CC");

        Category.setBackground(new java.awt.Color(255, 255, 255));
        Category.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Category.setText("Tìm SP/ Mã vạch");

        Suplier.setBackground(new java.awt.Color(255, 102, 0));
        Suplier.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Suplier.setText("Loại");

        FormCategory.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FormCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beverage", "Vegetable", "Meat", "Clothes", " " }));
        FormCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormCategoryActionPerformed(evt);
            }
        });

        SearchButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\search-interface-symbol.png")); // NOI18N
        SearchButton.setText("Tìm kiếm");
        SearchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        EditButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EditButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\edit.png")); // NOI18N
        EditButton.setText("Chỉnh sửa");
        EditButton.setBorder(null);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên SP", "Loại", "Giá bán", "Đơn vị", "Số lượng ", "Mã vạch", "Nhà CC", "Giá Nhập"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionForeground(new java.awt.Color(255, 102, 0));
        TableProducts.setViewportView(jTable1);

        ProductList.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ProductList.setText("DANH SÁCH SẢN PHẨM");

        FormCategory2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FormCategory2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beverage", "Vegetable", "Meat", "Clothes", " " }));
        FormCategory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormCategory2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boxProductsLayout = new javax.swing.GroupLayout(boxProducts);
        boxProducts.setLayout(boxProductsLayout);
        boxProductsLayout.setHorizontalGroup(
            boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxProductsLayout.createSequentialGroup()
                .addGap(0, 396, Short.MAX_VALUE)
                .addComponent(ProductList)
                .addGap(397, 397, 397))
            .addGroup(boxProductsLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FormCategory2, 0, 240, Short.MAX_VALUE)
                    .addComponent(FormProdID))
                .addGap(150, 150, 150)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addComponent(Suplier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(FormCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(boxProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TableProducts))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxProductsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ManageProducts)
                .addGap(415, 415, 415))
        );
        boxProductsLayout.setVerticalGroup(
            boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxProductsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ManageProducts)
                .addGap(26, 26, 26)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Name)
                        .addComponent(FormCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Suplier)
                        .addComponent(FormCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FormProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Category)))
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addComponent(ProductList)
                .addGap(24, 24, 24)
                .addComponent(TableProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenu6.setText("Nhập Hàng");
        jMenuBar1.add(jMenu6);

        jMenu3.setText("Sản Phẩm");
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Hoá Đơn");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Khách Hàng");
        jMenuBar1.add(jMenu1);

        jMenu7.setText("Nhân Viên");
        jMenuBar1.add(jMenu7);

        jMenu4.setText("Báo Cáo");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Hệ Thống");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    private void FormCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormCategoryActionPerformed

    private void FormCategory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormCategory2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormCategory2ActionPerformed

    private void FormProdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormProdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormProdIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Category;
    private javax.swing.JButton EditButton;
    private javax.swing.JComboBox<String> FormCategory;
    private javax.swing.JComboBox<String> FormCategory2;
    private javax.swing.JTextField FormProdID;
    private javax.swing.JLabel ManageProducts;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel ProductList;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel Suplier;
    private javax.swing.JScrollPane TableProducts;
    private javax.swing.JPanel boxProducts;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
