/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Market;

/**
 *
 * @author ADMIN
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boxProducts = new javax.swing.JPanel();
        ManageProducts = new javax.swing.JLabel();
        FormName = new javax.swing.JTextField();
        FormProdID = new javax.swing.JTextField();
        ProdID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        FormPrice = new javax.swing.JTextField();
        Category = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Unit = new javax.swing.JLabel();
        FormCategory = new javax.swing.JComboBox<>();
        AddButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        FormUnit = new javax.swing.JTextField();
        TableProducts = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ProductList = new javax.swing.JLabel();
        FormBarcode = new javax.swing.JTextField();
        Barcode = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        FormQuantity = new javax.swing.JTextField();
        Quantity = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 800));

        boxProducts.setPreferredSize(new java.awt.Dimension(1200, 775));
        boxProducts.setRequestFocusEnabled(false);

        ManageProducts.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ManageProducts.setForeground(new java.awt.Color(255, 102, 51));
        ManageProducts.setText("MANAGE STOCK");

        FormName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormName.setForeground(new java.awt.Color(255, 102, 0));
        FormName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormNameActionPerformed(evt);
            }
        });

        FormProdID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormProdID.setForeground(new java.awt.Color(255, 102, 0));

        ProdID.setBackground(new java.awt.Color(255, 102, 0));
        ProdID.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        ProdID.setForeground(new java.awt.Color(255, 102, 51));
        ProdID.setText("PRODID");

        Name.setBackground(new java.awt.Color(255, 102, 0));
        Name.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 102, 51));
        Name.setText("NAME");

        FormPrice.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormPrice.setForeground(new java.awt.Color(255, 102, 0));
        FormPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormPriceActionPerformed(evt);
            }
        });

        Category.setBackground(new java.awt.Color(255, 102, 0));
        Category.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Category.setForeground(new java.awt.Color(255, 102, 51));
        Category.setText("CATEGORY");

        Price.setBackground(new java.awt.Color(255, 102, 0));
        Price.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 102, 51));
        Price.setText("PRICE");

        Unit.setBackground(new java.awt.Color(255, 102, 0));
        Unit.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Unit.setForeground(new java.awt.Color(255, 102, 51));
        Unit.setText("UNIT");

        FormCategory.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FormCategory.setForeground(new java.awt.Color(255, 102, 0));
        FormCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beverage", "Vegetable", "Meat", "Clothes", " " }));
        FormCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormCategoryActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(204, 204, 204));
        AddButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 102, 0));
        AddButton.setText("Add");
        AddButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        EditButton.setBackground(new java.awt.Color(204, 204, 204));
        EditButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        EditButton.setForeground(new java.awt.Color(255, 102, 0));
        EditButton.setText("Edit");
        EditButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        FormUnit.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormUnit.setForeground(new java.awt.Color(255, 102, 0));
        FormUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormUnitActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Price", "Unit", "Barcode", "Quantity"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionForeground(new java.awt.Color(255, 102, 0));
        TableProducts.setViewportView(jTable1);

        ProductList.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ProductList.setForeground(new java.awt.Color(255, 102, 51));
        ProductList.setText("STOCK LIST");

        FormBarcode.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormBarcode.setForeground(new java.awt.Color(255, 102, 0));
        FormBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormBarcodeActionPerformed(evt);
            }
        });

        Barcode.setBackground(new java.awt.Color(255, 102, 0));
        Barcode.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Barcode.setForeground(new java.awt.Color(255, 102, 51));
        Barcode.setText("BARCODE");

        DeleteButton.setBackground(new java.awt.Color(204, 204, 204));
        DeleteButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 102, 0));
        DeleteButton.setText("Delete");
        DeleteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(204, 204, 204));
        ClearButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(255, 102, 0));
        ClearButton.setText("Clear");
        ClearButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        FormQuantity.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormQuantity.setForeground(new java.awt.Color(255, 102, 0));
        FormQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormQuantityActionPerformed(evt);
            }
        });

        Quantity.setBackground(new java.awt.Color(255, 102, 0));
        Quantity.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Quantity.setForeground(new java.awt.Color(255, 102, 51));
        Quantity.setText("QUANTITY");

        javax.swing.GroupLayout boxProductsLayout = new javax.swing.GroupLayout(boxProducts);
        boxProducts.setLayout(boxProductsLayout);
        boxProductsLayout.setHorizontalGroup(
            boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxProductsLayout.createSequentialGroup()
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(boxProductsLayout.createSequentialGroup()
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProdID)
                                    .addComponent(Name))
                                .addGap(57, 57, 57)
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FormName)
                                    .addComponent(FormProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, boxProductsLayout.createSequentialGroup()
                                .addComponent(Category)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FormCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Price)
                            .addComponent(Unit)
                            .addComponent(Barcode)
                            .addComponent(Quantity))
                        .addGap(24, 24, 24)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FormPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FormUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FormBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FormQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(TableProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxProductsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxProductsLayout.createSequentialGroup()
                        .addComponent(ManageProducts)
                        .addGap(495, 495, 495))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxProductsLayout.createSequentialGroup()
                        .addComponent(ProductList)
                        .addGap(527, 527, 527))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxProductsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        boxProductsLayout.setVerticalGroup(
            boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManageProducts)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(FormProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FormName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Category)
                            .addComponent(FormCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(boxProductsLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(ProdID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Name))
                            .addGroup(boxProductsLayout.createSequentialGroup()
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FormPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Price))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FormUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Unit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Barcode)
                                    .addComponent(FormBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FormQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity))
                .addGap(24, 24, 24)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProductList)
                .addGap(18, 18, 18)
                .addComponent(TableProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        Close.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\close.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Close, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boxProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1217, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormNameActionPerformed

    private void FormPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormPriceActionPerformed

    private void FormCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormCategoryActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    private void FormUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormUnitActionPerformed

    private void FormBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormBarcodeActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void FormQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel Barcode;
    private javax.swing.JLabel Category;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel Close;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField FormBarcode;
    private javax.swing.JComboBox<String> FormCategory;
    private javax.swing.JTextField FormName;
    private javax.swing.JTextField FormPrice;
    private javax.swing.JTextField FormProdID;
    private javax.swing.JTextField FormQuantity;
    private javax.swing.JTextField FormUnit;
    private javax.swing.JLabel ManageProducts;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel ProdID;
    private javax.swing.JLabel ProductList;
    private javax.swing.JLabel Quantity;
    private javax.swing.JScrollPane TableProducts;
    private javax.swing.JLabel Unit;
    private javax.swing.JPanel boxProducts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
