/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.retail.view;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.io.UnsupportedEncodingException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Main extends javax.swing.JFrame {

    private final CardLayout cardLayout;
    private final StockMenuPanel stockMenuPanel;
    private final BackgroundPanel backgroundPanel;
    private final EmployeePanel employeePanel;
    private final SupplierPanel supplierPanel;
    private final StockEntryListPanel entryListPanel;
    private final SystemPanel systempanel;
    private final ChangepassPanel changepassPanel;
    private final String loggedInUser;
    private final String userRole;
    private final ProductPanel productPanel;
    private final ReportPanel reportPanel;
    private final CustomerPanel customerPanel;
    private final InvoicePanel invoicePanel;

    /**
     * Creates new form Menu
     *
     * @param role
     * @param username
     */
    public Main(String role, String username) {
        setTitle("Quản lý cửa hàng tạp hóa");
        this.loggedInUser = username;
        this.userRole = role;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        // Thiết lập CardLayout
        cardLayout = new CardLayout();
        ContentPanel.setLayout(cardLayout);

        Dimension panelSize = ContentPanel.getPreferredSize();

        backgroundPanel = new BackgroundPanel();
        backgroundPanel.setPreferredSize(panelSize);
        backgroundPanel.setMinimumSize(panelSize);
        backgroundPanel.setMaximumSize(panelSize);

        stockMenuPanel = new StockMenuPanel();
        stockMenuPanel.setPreferredSize(panelSize);
        stockMenuPanel.setMinimumSize(panelSize);
        stockMenuPanel.setMaximumSize(panelSize);

        employeePanel = new EmployeePanel();
        employeePanel.setPreferredSize(panelSize);
        employeePanel.setMinimumSize(panelSize);
        employeePanel.setMaximumSize(panelSize);

        supplierPanel = new SupplierPanel();
        supplierPanel.setPreferredSize(panelSize);
        supplierPanel.setMinimumSize(panelSize);
        supplierPanel.setMaximumSize(panelSize);

        entryListPanel = new StockEntryListPanel();
        entryListPanel.setPreferredSize(panelSize);
        entryListPanel.setMinimumSize(panelSize);
        entryListPanel.setMaximumSize(panelSize);

        productPanel = new ProductPanel();
        productPanel.setPreferredSize(panelSize);
        productPanel.setMinimumSize(panelSize);
        productPanel.setMaximumSize(panelSize);

        reportPanel = new ReportPanel();
        reportPanel.setPreferredSize(panelSize);
        reportPanel.setMinimumSize(panelSize);
        reportPanel.setMaximumSize(panelSize);

        customerPanel = new CustomerPanel();
        customerPanel.setPreferredSize(panelSize);
        customerPanel.setMinimumSize(panelSize);
        customerPanel.setMaximumSize(panelSize);

        invoicePanel = new InvoicePanel();
        invoicePanel.setPreferredSize(panelSize);
        invoicePanel.setMinimumSize(panelSize);
        invoicePanel.setMaximumSize(panelSize);

        systempanel = new SystemPanel(this);

        changepassPanel = new ChangepassPanel(loggedInUser);

        // Thêm các panel vào contentPanel
        ContentPanel.add(backgroundPanel, "Background");
        ContentPanel.add(stockMenuPanel, "Stock");
        ContentPanel.add(employeePanel, "Employee");
        ContentPanel.add(supplierPanel, "Supplier");
        ContentPanel.add(entryListPanel, "Entry");
        ContentPanel.add(systempanel, "System");
        ContentPanel.add(changepassPanel, "Changepass");
        ContentPanel.add(productPanel, "Product");
        ContentPanel.add(reportPanel, "Report");
        ContentPanel.add(customerPanel, "Customer");
        ContentPanel.add(invoicePanel, "Invoice");
        

        // Hiển thị màn hình mặc định
        cardLayout.show(ContentPanel, "Background");

        // Thêm sự kiện và hiệu ứng
    }

    public void showChangePasswordPanel() {
        cardLayout.show(ContentPanel, "Changepass");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBarPanel10 = new javax.swing.JPanel();
        SupplierPage10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        SupplierButton10 = new javax.swing.JButton();
        ImportPage = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        ImportButton = new javax.swing.JButton();
        ProductPage = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        ProductButton = new javax.swing.JButton();
        CustomerPage = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        CustomerButton = new javax.swing.JButton();
        EmployeePage = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        EmployeeButton = new javax.swing.JButton();
        InvoicePage = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        InvoiceButton = new javax.swing.JButton();
        SystemPage = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        SystemButton = new javax.swing.JButton();
        ReportPage = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        ReportButton = new javax.swing.JButton();
        Logout = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        ContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SideBarPanel10.setBackground(new java.awt.Color(255, 102, 0));
        SideBarPanel10.setPreferredSize(new java.awt.Dimension(200, 900));

        SupplierPage10.setBackground(new java.awt.Color(255, 255, 255));
        SupplierPage10.setPreferredSize(new java.awt.Dimension(120, 80));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Nhà CC");

        SupplierButton10.setBackground(new java.awt.Color(255, 193, 153));
        SupplierButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supplier.png"))); // NOI18N
        SupplierButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierButton10SupplierButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SupplierPage10Layout = new javax.swing.GroupLayout(SupplierPage10);
        SupplierPage10.setLayout(SupplierPage10Layout);
        SupplierPage10Layout.setHorizontalGroup(
            SupplierPage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SupplierButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SupplierPage10Layout.setVerticalGroup(
            SupplierPage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierPage10Layout.createSequentialGroup()
                .addComponent(SupplierButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22))
        );

        ImportPage.setBackground(new java.awt.Color(255, 255, 255));
        ImportPage.setPreferredSize(new java.awt.Dimension(120, 80));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("QL Nhập Kho");

        ImportButton.setBackground(new java.awt.Color(255, 193, 153));
        ImportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/import.png"))); // NOI18N
        ImportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportButtonMouseClicked(evt);
            }
        });
        ImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ImportPageLayout = new javax.swing.GroupLayout(ImportPage);
        ImportPage.setLayout(ImportPageLayout);
        ImportPageLayout.setHorizontalGroup(
            ImportPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(ImportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ImportPageLayout.setVerticalGroup(
            ImportPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImportPageLayout.createSequentialGroup()
                .addComponent(ImportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23))
        );

        ProductPage.setBackground(new java.awt.Color(255, 255, 255));
        ProductPage.setPreferredSize(new java.awt.Dimension(120, 80));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Sản Phẩm");

        ProductButton.setBackground(new java.awt.Color(255, 193, 153));
        ProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/products.png"))); // NOI18N
        ProductButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProductPageLayout = new javax.swing.GroupLayout(ProductPage);
        ProductPage.setLayout(ProductPageLayout);
        ProductPageLayout.setHorizontalGroup(
            ProductPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ProductPageLayout.setVerticalGroup(
            ProductPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPageLayout.createSequentialGroup()
                .addComponent(ProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24))
        );

        CustomerPage.setBackground(new java.awt.Color(255, 255, 255));
        CustomerPage.setPreferredSize(new java.awt.Dimension(120, 80));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Khách Hàng");

        CustomerButton.setBackground(new java.awt.Color(255, 193, 153));
        CustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/service.png"))); // NOI18N
        CustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CustomerPageLayout = new javax.swing.GroupLayout(CustomerPage);
        CustomerPage.setLayout(CustomerPageLayout);
        CustomerPageLayout.setHorizontalGroup(
            CustomerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CustomerPageLayout.setVerticalGroup(
            CustomerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPageLayout.createSequentialGroup()
                .addComponent(CustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25))
        );

        EmployeePage.setBackground(new java.awt.Color(255, 255, 255));
        EmployeePage.setPreferredSize(new java.awt.Dimension(120, 80));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Nhân Viên");

        EmployeeButton.setBackground(new java.awt.Color(255, 193, 153));
        EmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/division.png"))); // NOI18N
        EmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EmployeePageLayout = new javax.swing.GroupLayout(EmployeePage);
        EmployeePage.setLayout(EmployeePageLayout);
        EmployeePageLayout.setHorizontalGroup(
            EmployeePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EmployeePageLayout.setVerticalGroup(
            EmployeePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePageLayout.createSequentialGroup()
                .addComponent(EmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26))
        );

        InvoicePage.setBackground(new java.awt.Color(255, 255, 255));
        InvoicePage.setPreferredSize(new java.awt.Dimension(120, 80));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Hoá Đơn");

        InvoiceButton.setBackground(new java.awt.Color(255, 193, 153));
        InvoiceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice.png"))); // NOI18N
        InvoiceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoiceButtonMouseClicked(evt);
            }
        });
        InvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InvoicePageLayout = new javax.swing.GroupLayout(InvoicePage);
        InvoicePage.setLayout(InvoicePageLayout);
        InvoicePageLayout.setHorizontalGroup(
            InvoicePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InvoiceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InvoicePageLayout.setVerticalGroup(
            InvoicePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePageLayout.createSequentialGroup()
                .addComponent(InvoiceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SystemPage.setBackground(new java.awt.Color(255, 255, 255));
        SystemPage.setForeground(new java.awt.Color(255, 255, 255));
        SystemPage.setPreferredSize(new java.awt.Dimension(120, 80));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Hệ Thống");

        SystemButton.setBackground(new java.awt.Color(255, 193, 153));
        SystemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-integration.png"))); // NOI18N
        SystemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SystemButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SystemPageLayout = new javax.swing.GroupLayout(SystemPage);
        SystemPage.setLayout(SystemPageLayout);
        SystemPageLayout.setHorizontalGroup(
            SystemPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SystemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SystemPageLayout.setVerticalGroup(
            SystemPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SystemPageLayout.createSequentialGroup()
                .addComponent(SystemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28))
        );

        ReportPage.setBackground(new java.awt.Color(255, 255, 255));
        ReportPage.setPreferredSize(new java.awt.Dimension(120, 80));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Báo Cáo");

        ReportButton.setBackground(new java.awt.Color(255, 193, 153));
        ReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        ReportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ReportPageLayout = new javax.swing.GroupLayout(ReportPage);
        ReportPage.setLayout(ReportPageLayout);
        ReportPageLayout.setHorizontalGroup(
            ReportPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ReportPageLayout.setVerticalGroup(
            ReportPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportPageLayout.createSequentialGroup()
                .addComponent(ReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29))
        );

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.setPreferredSize(new java.awt.Dimension(120, 80));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Thoát");

        LogoutButton.setBackground(new java.awt.Color(255, 193, 153));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutLayout.createSequentialGroup()
                .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30))
        );

        javax.swing.GroupLayout SideBarPanel10Layout = new javax.swing.GroupLayout(SideBarPanel10);
        SideBarPanel10.setLayout(SideBarPanel10Layout);
        SideBarPanel10Layout.setHorizontalGroup(
            SideBarPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarPanel10Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(SideBarPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SystemPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InvoicePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomerPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImportPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SupplierPage10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReportPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        SideBarPanel10Layout.setVerticalGroup(
            SideBarPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(SupplierPage10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(ImportPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(ProductPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(CustomerPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(EmployeePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(InvoicePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(SystemPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ReportPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1235, Short.MAX_VALUE)
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SideBarPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBarPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
            .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn thoát không?",
                "Xác nhận đăng xuất",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0); // Thoát hoàn toàn chương trình
        }
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void ReportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportButtonMouseClicked
        if ("manager".equalsIgnoreCase(userRole) || "cashier".equalsIgnoreCase(userRole)) {
            cardLayout.show(ContentPanel, "Report");
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào Báo Cáo!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ReportButtonMouseClicked

    private void SystemButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SystemButtonMouseClicked
        cardLayout.show(ContentPanel, "System");
    }//GEN-LAST:event_SystemButtonMouseClicked

    private void InvoiceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceButtonMouseClicked
        if ("manager".equalsIgnoreCase(userRole) || "cashier".equalsIgnoreCase(userRole)) {
            cardLayout.show(ContentPanel, "Invoice");
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào Hoá Đơn!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_InvoiceButtonMouseClicked

    private void EmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeButtonMouseClicked
        if ("manager".equalsIgnoreCase(userRole)) {
            cardLayout.show(ContentPanel, "Employee");
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào Nhân Viên!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EmployeeButtonMouseClicked

    private void CustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerButtonMouseClicked
        cardLayout.show(ContentPanel, "Customer");
    }//GEN-LAST:event_CustomerButtonMouseClicked

    private void ProductButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButtonMouseClicked
        cardLayout.show(ContentPanel, "Product");
    }//GEN-LAST:event_ProductButtonMouseClicked

    private void ImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportButtonActionPerformed

    }//GEN-LAST:event_ImportButtonActionPerformed

    private void ImportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportButtonMouseClicked
       if ("manager".equalsIgnoreCase(userRole)|| "stock_keeper".equalsIgnoreCase(userRole)) {
            cardLayout.show(ContentPanel, "Stock");
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào kho hàng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ImportButtonMouseClicked

    private void SupplierButton10SupplierButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierButton10SupplierButtonMouseClicked
        cardLayout.show(ContentPanel, "Supplier");
    }//GEN-LAST:event_SupplierButton10SupplierButtonMouseClicked

    private void InvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InvoiceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            System.setOut(new java.io.PrintStream(System.out, true, "UTF-8"));
        } catch (UnsupportedEncodingException e) {
            System.out.println("Lỗi khi đặt encoding UTF-8!");
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JButton CustomerButton;
    private javax.swing.JPanel CustomerPage;
    private javax.swing.JButton EmployeeButton;
    private javax.swing.JPanel EmployeePage;
    private javax.swing.JButton ImportButton;
    private javax.swing.JPanel ImportPage;
    private javax.swing.JButton InvoiceButton;
    private javax.swing.JPanel InvoicePage;
    private javax.swing.JPanel Logout;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ProductButton;
    private javax.swing.JPanel ProductPage;
    private javax.swing.JButton ReportButton;
    private javax.swing.JPanel ReportPage;
    private javax.swing.JPanel SideBarPanel10;
    private javax.swing.JButton SupplierButton10;
    private javax.swing.JPanel SupplierPage10;
    private javax.swing.JButton SystemButton;
    private javax.swing.JPanel SystemPage;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    // End of variables declaration//GEN-END:variables
}
