/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Market;

/**
 *
 * @author ADMIN
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boxProducts = new javax.swing.JPanel();
        ManageProducts = new javax.swing.JLabel();
        FormName = new javax.swing.JTextField();
        FormProdID = new javax.swing.JTextField();
        ProdID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        FormQuantity = new javax.swing.JTextField();
        Category = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        FormCategory = new javax.swing.JComboBox<>();
        SearchButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        FormPrice = new javax.swing.JTextField();
        TableProducts = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ProductList = new javax.swing.JLabel();
        FormBarcode = new javax.swing.JTextField();
        Barcode = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(240, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 800));

        boxProducts.setPreferredSize(new java.awt.Dimension(1200, 775));
        boxProducts.setRequestFocusEnabled(false);

        ManageProducts.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ManageProducts.setForeground(new java.awt.Color(255, 102, 51));
        ManageProducts.setText("MANAGE PRODUCTS");

        FormName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormName.setForeground(new java.awt.Color(255, 102, 0));
        FormName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormNameActionPerformed(evt);
            }
        });

        FormProdID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormProdID.setForeground(new java.awt.Color(255, 102, 0));

        ProdID.setBackground(new java.awt.Color(255, 102, 0));
        ProdID.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        ProdID.setForeground(new java.awt.Color(255, 102, 51));
        ProdID.setText("PRODID");

        Name.setBackground(new java.awt.Color(255, 102, 0));
        Name.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 102, 51));
        Name.setText("NAME");

        FormQuantity.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormQuantity.setForeground(new java.awt.Color(255, 102, 0));
        FormQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormQuantityActionPerformed(evt);
            }
        });

        Category.setBackground(new java.awt.Color(255, 102, 0));
        Category.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Category.setForeground(new java.awt.Color(255, 102, 51));
        Category.setText("CATEGORY");

        Quantity.setBackground(new java.awt.Color(255, 102, 0));
        Quantity.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Quantity.setForeground(new java.awt.Color(255, 102, 51));
        Quantity.setText("QUANTITY");

        Price.setBackground(new java.awt.Color(255, 102, 0));
        Price.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 102, 51));
        Price.setText("PRICE");

        FormCategory.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FormCategory.setForeground(new java.awt.Color(255, 102, 0));
        FormCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beverage", "Vegetable", "Meat", "Clothes", " " }));
        FormCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormCategoryActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(204, 204, 204));
        SearchButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 102, 0));
        SearchButton.setText("Search");
        SearchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        EditButton.setBackground(new java.awt.Color(204, 204, 204));
        EditButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        EditButton.setForeground(new java.awt.Color(255, 102, 0));
        EditButton.setText("Edit");
        EditButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        FormPrice.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormPrice.setForeground(new java.awt.Color(255, 102, 0));
        FormPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormPriceActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Price", "Unit", "Supplier_ID", "barcode", "Stock_quantity"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionForeground(new java.awt.Color(255, 102, 0));
        TableProducts.setViewportView(jTable1);

        ProductList.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ProductList.setForeground(new java.awt.Color(255, 102, 51));
        ProductList.setText("PRODUCT LIST");

        FormBarcode.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormBarcode.setForeground(new java.awt.Color(255, 102, 0));
        FormBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormBarcodeActionPerformed(evt);
            }
        });

        Barcode.setBackground(new java.awt.Color(255, 102, 0));
        Barcode.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Barcode.setForeground(new java.awt.Color(255, 102, 51));
        Barcode.setText("BARCODE");

        javax.swing.GroupLayout boxProductsLayout = new javax.swing.GroupLayout(boxProducts);
        boxProducts.setLayout(boxProductsLayout);
        boxProductsLayout.setHorizontalGroup(
            boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxProductsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ManageProducts)
                .addGap(495, 495, 495))
            .addGroup(boxProductsLayout.createSequentialGroup()
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(boxProductsLayout.createSequentialGroup()
                                    .addGap(177, 177, 177)
                                    .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(boxProductsLayout.createSequentialGroup()
                                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(177, 177, 177)))
                            .addGroup(boxProductsLayout.createSequentialGroup()
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(boxProductsLayout.createSequentialGroup()
                                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ProdID)
                                            .addComponent(Name))
                                        .addGap(57, 57, 57)
                                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(FormName)
                                            .addComponent(FormProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, boxProductsLayout.createSequentialGroup()
                                        .addComponent(Category)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FormCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Quantity)
                                    .addComponent(Price)
                                    .addComponent(Barcode))))
                        .addGap(24, 24, 24)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FormQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FormPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FormBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(535, 535, 535)
                        .addComponent(ProductList))
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(TableProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        boxProductsLayout.setVerticalGroup(
            boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManageProducts)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(FormProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FormName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Category)
                            .addComponent(FormCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(boxProductsLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(boxProductsLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(ProdID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Name))
                            .addGroup(boxProductsLayout.createSequentialGroup()
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FormQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Quantity))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FormPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Price))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FormBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Barcode))))))
                .addGap(40, 40, 40)
                .addGroup(boxProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(ProductList)
                .addGap(18, 18, 18)
                .addComponent(TableProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        Close.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\close.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 1205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FormNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormNameActionPerformed

    private void FormQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormQuantityActionPerformed

    private void FormPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormPriceActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    private void FormBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormBarcodeActionPerformed

    private void FormCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barcode;
    private javax.swing.JLabel Category;
    private javax.swing.JLabel Close;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField FormBarcode;
    private javax.swing.JComboBox<String> FormCategory;
    private javax.swing.JTextField FormName;
    private javax.swing.JTextField FormPrice;
    private javax.swing.JTextField FormProdID;
    private javax.swing.JTextField FormQuantity;
    private javax.swing.JLabel ManageProducts;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel ProdID;
    private javax.swing.JLabel ProductList;
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton SearchButton;
    private javax.swing.JScrollPane TableProducts;
    private javax.swing.JPanel boxProducts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
