/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.retail.view;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class StockMenuPanel extends javax.swing.JPanel {
     private CardLayout cardLayout;
    private StockEntryPanel stockEntryPanel; // Khai báo biến
    private InventoryPanel inventoryPanel;

    /**
     * Creates new form StockMenuPanel
     */
    public StockMenuPanel() {
        initComponents();
        

        // Khởi tạo các panel
        stockEntryPanel = new StockEntryPanel(); // Khởi tạo StockEntryPanel
        StockEntryListPanel stockEntryListPanel = new StockEntryListPanel();
        inventoryPanel = new InventoryPanel();

        // Thiết lập CardLayout
        cardLayout = new CardLayout();
        contentPanel.setLayout(cardLayout);

        // Thêm các panel vào contentPanel
        contentPanel.add(stockEntryPanel, "StockEntry");
        contentPanel.add(stockEntryListPanel, "StockEntryList");
        contentPanel.add(inventoryPanel, "Inventory");

        // Hiển thị màn hình mặc định
        cardLayout.show(contentPanel, "StockEntryList");

        // Thêm sự kiện và hiệu ứng
        addLabelListeners();
        addLabelHoverEffects();
    }
    
    public StockEntryPanel getStockEntryPanel() {
        return stockEntryPanel; // Trả về instance của StockEntryPanel
    }

    public void showPanel(String panelName) {
        cardLayout.show(contentPanel, panelName); // Chuyển đổi panel bằng CardLayout
    }

    private void addLabelListeners() {
        // Thêm MouseListener cho từng JLabel
        addStockEntryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardLayout.show(contentPanel, "StockEntry"); // Hiển thị panel StockEntry
                stockEntryPanel.initializeData(); // Gọi lại phương thức initializeData()
            }
        });

        stockEntryListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardLayout.show(contentPanel, "StockEntryList"); // Hiển thị panel Function1
            }
        });

        InventoryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardLayout.show(contentPanel, "Inventory"); // Hiển thị panel Function2
            }
        });


    }

    private void addLabelHoverEffects() {
        // Hiệu ứng cho addStockEntryLabel
        addHoverEffect(addStockEntryLabel);

        // Hiệu ứng cho stockEntryListLabel
        addHoverEffect(stockEntryListLabel);

        // Hiệu ứng cho InventoryLabel
        addHoverEffect(InventoryLabel);


    }

    private void addHoverEffect(JLabel label) {
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label.setForeground(Color.BLUE); // Đổi màu chữ khi di chuột qua
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label.setForeground(Color.BLACK); // Trả lại màu chữ ban đầu
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        stockEntryListLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addStockEntryLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        InventoryLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        sideBarPanel.setBackground(new java.awt.Color(255, 102, 0));
        sideBarPanel.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        stockEntryListLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockEntryListLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noteIcon.png"))); // NOI18N
        stockEntryListLabel.setText("PHIẾU NHẬP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stockEntryListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stockEntryListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        addStockEntryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addStockEntryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inIcon.png"))); // NOI18N
        addStockEntryLabel.setText("NHẬP HÀNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(addStockEntryLabel)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addStockEntryLabel)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        InventoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InventoryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invenIcon.png"))); // NOI18N
        InventoryLabel.setText("TỒN KHO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(InventoryLabel)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InventoryLabel)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(605, Short.MAX_VALUE))
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InventoryLabel;
    private javax.swing.JLabel addStockEntryLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel stockEntryListLabel;
    // End of variables declaration//GEN-END:variables
}
