/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.retail.view;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.UnsupportedEncodingException;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class StockSidebar extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private StockEntryPanel stockEntryPanel; // Khai báo biến
    private InventoryPanel inventoryPanel;

    public StockSidebar() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        // Khởi tạo các panel
        stockEntryPanel = new StockEntryPanel(); // Khởi tạo StockEntryPanel
        StockEntryListPanel stockEntryListPanel = new StockEntryListPanel();
        inventoryPanel = new InventoryPanel();
        StockMenuPanel stockMenuPanel = new StockMenuPanel();

        // Thiết lập CardLayout
        cardLayout = new CardLayout();
        contentPanel.setLayout(cardLayout);

        // Thêm các panel vào contentPanel
        contentPanel.add(stockEntryPanel, "StockEntry");
        contentPanel.add(stockEntryListPanel, "StockEntryList");
        contentPanel.add(inventoryPanel, "Inventory");
        contentPanel.add(stockMenuPanel, "Menu");

        // Hiển thị màn hình mặc định
        cardLayout.show(contentPanel, "StockEntryList");

        // Thêm sự kiện và hiệu ứng
        addLabelListeners();
        addLabelHoverEffects();
    }

    public StockEntryPanel getStockEntryPanel() {
        return stockEntryPanel; // Trả về instance của StockEntryPanel
    }

    public void showPanel(String panelName) {
        cardLayout.show(contentPanel, panelName); // Chuyển đổi panel bằng CardLayout
    }

    private void addLabelListeners() {
        // Thêm MouseListener cho từng JLabel
        addStockEntryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardLayout.show(contentPanel, "StockEntry"); // Hiển thị panel StockEntry
                stockEntryPanel.initializeData(); // Gọi lại phương thức initializeData()
            }
        });

        stockEntryListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardLayout.show(contentPanel, "StockEntryList"); // Hiển thị panel Function1
            }
        });

        InventoryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardLayout.show(contentPanel, "Inventory"); // Hiển thị panel Function2
            }
        });

        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                System.exit(0); // Thoát ứng dụng
                cardLayout.show(contentPanel, "Menu");
            }
        });
    }

    private void addLabelHoverEffects() {
        // Hiệu ứng cho addStockEntryLabel
        addHoverEffect(addStockEntryLabel);

        // Hiệu ứng cho stockEntryListLabel
        addHoverEffect(stockEntryListLabel);

        // Hiệu ứng cho InventoryLabel
        addHoverEffect(InventoryLabel);

        // Hiệu ứng cho exitLabel
        addHoverEffect(exitLabel);
    }

    private void addHoverEffect(JLabel label) {
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label.setForeground(Color.BLUE); // Đổi màu chữ khi di chuột qua
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label.setForeground(Color.WHITE); // Trả lại màu chữ ban đầu
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        stockEntryListLabel = new javax.swing.JLabel();
        addStockEntryLabel = new javax.swing.JLabel();
        InventoryLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sideBarPanel.setBackground(new java.awt.Color(255, 102, 0));
        sideBarPanel.setForeground(new java.awt.Color(255, 255, 255));

        stockEntryListLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockEntryListLabel.setForeground(new java.awt.Color(255, 255, 255));
        stockEntryListLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noteIcon.png"))); // NOI18N
        stockEntryListLabel.setText("PHIẾU NHẬP");

        addStockEntryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addStockEntryLabel.setForeground(new java.awt.Color(255, 255, 255));
        addStockEntryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inIcon.png"))); // NOI18N
        addStockEntryLabel.setText("NHẬP HÀNG");

        InventoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InventoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        InventoryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invenIcon.png"))); // NOI18N
        InventoryLabel.setText("TỒN KHO");

        exitLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exitIcon.png"))); // NOI18N
        exitLabel.setText("THOÁT");

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitLabel)
                    .addComponent(stockEntryListLabel)
                    .addComponent(addStockEntryLabel)
                    .addComponent(InventoryLabel))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(stockEntryListLabel)
                .addGap(67, 67, 67)
                .addComponent(addStockEntryLabel)
                .addGap(70, 70, 70)
                .addComponent(InventoryLabel)
                .addGap(63, 63, 63)
                .addComponent(exitLabel)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            System.setOut(new java.io.PrintStream(System.out, true, "UTF-8"));
        } catch (UnsupportedEncodingException e) {
            System.out.println("Lỗi khi đặt encoding UTF-8!");
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockSidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockSidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockSidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockSidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockSidebar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InventoryLabel;
    private javax.swing.JLabel addStockEntryLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel stockEntryListLabel;
    // End of variables declaration//GEN-END:variables
}
